name: Spell check Markdown files

# Controls when the action will run.
# Pull requests to master only.
on:
  pull_request:
    branches:
      - main
      - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "spell check"
  spell-check:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove files that do not need to be spellchecked
        run: |
          rm ./LICENSE

      - name: Spell check action
        uses: alexslemonade/spellcheck@v0
        id: spell
        with:
          dictionary: components/dictionary.txt

      - name: Upload spell check errors
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: spell_check_errors
          path: spell_check_errors.tsv

      - name: Fail if there are spelling errors
        if: steps.spell.outputs.error_count > 0
        run: |
          echo "There were ${{ steps.spell.outputs.error_count }} errors"
          column -t spell_check_errors.tsv
          exit 1
